#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: spark-lama-exps
---
apiVersion: v1
kind: ServiceAccount
metadata:
#  namespace: spark-lama-exps
  name: spark
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
#  namespace: spark-lama-exps
  name: spark-executor-creator
rules:
- apiGroups: ["*"]
  resources: ["pods", "pods/log", "pods/exec", "services", "configmaps", "persistentvolumeclaims" ]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-binding
#  namespace: spark-lama-exps
subjects:
- kind: ServiceAccount
  name: spark
roleRef:
  kind: Role
  name: spark-executor-creator
  apiGroup: rbac.authorization.k8s.io
