---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hadoop-env
data:
#  HADOOP_ROOT_LOGGER: "hadoop.root.logger=DEBUG,console"
  CORE_CONF_fs_defaultFS: "hdfs://node21.bdcl:9000"
  CORE_CONF_hadoop_http_staticuser_user: "root"
  CORE_CONF_hadoop_proxyuser_hue_hosts: "*"
  CORE_CONF_hadoop_proxyuser_hue_groups: "*"
  CORE_CONF_io_compression_codecs: "org.apache.hadoop.io.compress.SnappyCodec"
  YARN_CONF_yarn_log___aggregation___enable: "true"
  YARN_CONF_yarn_log_server_url: "http://yarn-history-server:8188/applicationhistory/logs/"
  YARN_CONF_yarn_resourcemanager_recovery_enabled: "true"
  YARN_CONF_yarn_resourcemanager_store_class: "org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore"
  YARN_CONF_yarn_resourcemanager_scheduler_class: "org.apache.hadoop.yarn.server.resourcemanager.scheduler.capacity.CapacityScheduler"
  YARN_CONF_yarn_scheduler_capacity_root_default_maximum___allocation___mb: "16384"
  YARN_CONF_yarn_scheduler_capacity_root_default_maximum___allocation___vcores: "8"
  YARN_CONF_yarn_scheduler_maximum___allocation___mb: "32768"
  YARN_CONF_yarn_scheduler_maximum___allocation___vcores: "8"
  YARN_CONF_yarn_resourcemanager_fs_state___store_uri: "/rmstate"
  YARN_CONF_yarn_resourcemanager_bind___host: "0.0.0.0"
  YARN_CONF_yarn_resourcemanager_hostname: "yarn-resourcemanager"
  YARN_CONF_yarn_resourcemanager_address: "yarn-resourcemanager:8032"
  YARN_CONF_yarn_resourcemanager_scheduler_address: "yarn-resourcemanager:8030"
  YARN_CONF_yarn_resourcemanager_resource__tracker_address: "yarn-resourcemanager:8031"
  YARN_CONF_yarn_timeline___service_enabled: "true"
  YARN_CONF_yarn_timeline___service_generic___application___history_enabled: "true"
  YAEN_CONF_yarn_timeline___service_bind___host: "0.0.0.0"
  YARN_CONF_yarn_timeline___service_hostname: "yarn-history-server"
  YARN_CONF_mapreduce_map_output_compress: "true"
  YARN_CONF_mapred_map_output_compress_codec: "org.apache.hadoop.io.compress.SnappyCodec"
  YARN_CONF_yarn_nodemanager_resource_memory___mb: "32768"
  YARN_CONF_yarn_nodemanager_resource_cpu___vcores: "8"
  YARN_CONF_yarn_nodemanager_disk___health___checker_max___disk___utilization___per___disk___percentage: "98.5"
  YARN_CONF_yarn_nodemanager_remote___app___log___dir: "/app-logs"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yarn-history-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yarn-history-server
  template:
    metadata:
      annotations:
        "sidecar.istio.io/inject": "false"
      labels:
        app: yarn-history-server
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: yarn-historyserver
      containers:
        - name: history-server
          image: node2.bdcl:5000/yarn-historyserver:slama-yarn
          imagePullPolicy: Always
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: hadoop-env
          ports:
            - containerPort: 8188
              name: http-webui
            - containerPort: 8190
              name: https-webui
            - containerPort: 10200
              name: rpc
          volumeMounts:
            - name: storage
              mountPath: /hadoop/yarn/timeline
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yarn-resourcemanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yarn-resourcemanager
  template:
    metadata:
      annotations:
        "sidecar.istio.io/inject": "false"
      labels:
        app: yarn-resourcemanager
    spec:
      hostname: yarn-resourcemanager
      containers:
        - name: resourcemanager
          image: node2.bdcl:5000/yarn-resourcemanager:slama-yarn
          imagePullPolicy: Always
          resources:
            requests:
              memory: "4Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: hadoop-env
          ports:
            - containerPort: 8030
              name: scheduler
            - containerPort: 8031
              name: rtracker
            - containerPort: 8032
              name: rmanager
            - containerPort: 8088
              name: http-webui
            - containerPort: 8090
              name: https-webui
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yarn-nodemanager
spec:
  serviceName: yarn-nms
  replicas: 1
  selector:
    matchLabels:
      app: yarn-nodemanager
  template:
    metadata:
      annotations:
        "sidecar.istio.io/inject": "false"
      labels:
        app: yarn-nodemanager
    spec:
      setHostnameAsFQDN: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: spark-lama-data
        - name: nfs
          persistentVolumeClaim:
            claimName: mnt-nfs
        - name: ephemeral
          emptyDir: {}
      containers:
        - name: nodemanager
          image: node2.bdcl:5000/yarn-nodemanager:slama-yarn
          imagePullPolicy: Always
          resources:
            requests:
              memory: "32Gi"
              cpu: "8"
            limits:
              memory: "32Gi"
              cpu: "8"
          envFrom:
            - configMapRef:
                name: hadoop-env
          ports:
            - containerPort: 8042
              name: http-webui
            - containerPort: 8044
              name: https-webui
          volumeMounts:
            - name: data
              mountPath: /opt/spark_data/
            - name: nfs
              mountPath: /mnt/nfs/
            # hadoop tmp dir
            - name: ephemeral
              mountPath: "/tmp"
---
apiVersion: v1
kind: Service
metadata:
  name: yarn-history-server
spec:
  type: NodePort
  ports:
    - port: 8188
      name: http-webui
    - port: 8190
      name: https-webui
    - port: 10200
      name: rpc
  selector:
    app: yarn-history-server
---
apiVersion: v1
kind: Service
metadata:
  name: yarn-resourcemanager
spec:
  type: NodePort
  ports:
    - port: 8030
      name: scheduler
    - port: 8031
      name: resource-tracker
    - port: 8032
      name: resource-manager
    - port: 8088
      name: http-webui
    - port: 8090
      name: https-webui
  selector:
    app: yarn-resourcemanager
---
apiVersion: v1
kind: Service
metadata:
  name: yarn-nms
spec:
  clusterIP: None
  ports:
    - port: 8042
      name: http-webui
    - port: 8044
      name: https-webui
  selector:
    app: yarn-nodemanager
